### ISSUE TITLE
Cannot compile 2.1.1 version

### ISSUE THREAD

**Issue by BULL3TB0T** [spumer/Left4Fix#11]
> C:\Users\BULLETBOT\Downloads\Left4Fix-2.1.1>python configure.py --team-size 10
Warning: build is being configured in the source tree.
Re-using build folder: obj-windows-AMD64
Checking CC compiler (vendor test msvc)... ['C:\\mingw64\\bin\\gcc.exe', 'test.c', '-o', 'test.exe', '-nologo', '-showIncludes']
failed with return code 1
Checking CC compiler (vendor test gcc)... ['C:\\mingw64\\bin\\gcc.exe', 'test.c', '-o', 'test.exe']
found gcc version 13.1
Checking CXX compiler (vendor test msvc)... ['C:\\mingw64\\bin\\g++.exe', 'test.cpp', '-o', 'testp.exe', '-nologo', '-showIncludes']
failed with return code 1
Checking CXX compiler (vendor test gcc)... ['C:\\mingw64\\bin\\g++.exe', 'test.cpp', '-o', 'testp.exe']
found gcc version 13.1

> C:\Users\BULLETBOT\Downloads\Left4Fix-2.1.1>ambuild
Error: folder was not configured for AMBuild.

**Comment by spumer** [comment]
You can download latest Windows build from Github: https://github.com/spumer/Left4Fix?tab=readme-ov-file#how-to-get-latest-build

Or try to configure in different folder like in build workflow:
https://github.com/spumer/Left4Fix/blob/master/.github/workflows/build.yaml#L137

**Comment by BULL3TB0T** [comment]
I would like to build it with team-size 2 but for some reason it wouldn't let me build it shown above. What could be the issue?

**Comment by BULL3TB0T** [comment]
Why is this so hard to build, you should make steps on how to compile this stuff because some people probably needs this in the future and want to use custom team-size, why is this not implemented as a cvar yet?

**Comment by spumer** [comment]
Build steps are represented in https://github.com/spumer/Left4Fix/blob/master/.github/workflows/build.yaml

You can fork this repo and update build.yaml with own TEAM_SIZE and download result from artifacts

**Comment by BULL3TB0T** [comment]
That worked out, thanks.
