### ISSUE TITLE
Crash on 8 players version

### ISSUE THREAD

**Issue by spumer** [spumer/Left4Fix#3]
https://forums.alliedmods.net/showpost.php?p=2719285&postcount=152

Looks like offsets for https://github.com/spumer/Left4Fix/blob/master/src/codepatch/score_code_lite.cpp are wrong.
But i'm chek it before :(

Ok, need check again

**Comment by Skarred1** [comment]
#1

**Comment by Skarred1** [comment]
Duplicate of #

**Comment by spumer** [comment]
Fixed in https://github.com/spumer/Left4Fix/pull/5
