### ISSUE TITLE
Defib causing distance points to double

### ISSUE THREAD

**Issue by Satanic-Spirit** [spumer/Left4Fix#9]
There is a major bug with the extension right now. 

Steps to reproduce:

- Change survivor count to 8. 
- Go half-way through the map.
- Kill a survivor and then use a defib. 

You will notice that distance score jumps. It is counting the score twice for the survivor who just got revived. 

My suspicions are that event_player_death is not adding the dead player to g_dead_players array.

**Comment by spumer** [comment]
Bug occured when you use 8players version?

**Comment by Satanic-Spirit** [comment]
Yeah 8 player version.

**Comment by spumer** [comment]
Fixed
